#! /usr/bin/env bash

# NOTE: Using exported variables here so they are not in main.tf
# Typically the contents of this file would be contained in your
# build platform of choice. This file is purely for demonstration
# purposes.
export TF_HTTP_USERNAME=myUser
export TF_HTTP_PASSWORD=password

rm -rf ./terraform/mdsCloudServerlessFunctions-sampleApp.zip
zip -r ./terraform/mdsCloudServerlessFunctions-sampleApp.zip . \
  -x "./terraform/*" \
  -x "./.git/*" \
  -x "./.vscode/*" \
  -x "./node_modules/*" \
  -x run-terraform \
  -x README.md \
  -x LICENSE \
  -x .gitignore \
  -q

rm -rf ./terraform/.terraform/ ./terraform/.terraform.lock.hcl
terraform -chdir=./terraform init
terraform -chdir=./terraform apply --auto-approve --var-file=./test.tfvars
